name: 新的API接口
description: "某个API接口在本项目中没有"
labels: [新特性]
body:
- type: textarea
  id: request
  attributes:
    label: 描述
    placeholder: 简要描述一下接口的含义
  validations:
    required: true

- type: textarea
  id: response
  attributes:
    label: 接口文档
    placeholder: |-
      可以贴上接口文档的链接

      也可以直接贴上接口 url 和各字段含义
  validations:
    required: true

- type: textarea
  id: expecting
  attributes:
    label: 请求和返回的例子
